syntax = "proto3";
package pokemonpricer.cards;
option java_package = "com.pokemonpricer.pokemoncardsservice.grpc";
option java_multiple_files = true;

service PokemonCardsService {
  rpc GetCards (GetCardsRequest) returns (GetCardsResponse);
}

message GetCardsRequest {
  string name = 1;
  string set = 2;
  int32 page = 3;
  int32 number_of_items = 4;
}

message Card {
  string id = 1;
  string name = 2;
  string set = 3;
  string image_url = 4;
}

message GetCardsResponse {
  repeated Card cards = 1;
}
