syntax = "proto3";
package pokemonpricer.prices;
option java_package = "com.pokemonpricer.pokemonpricesservice.grpc";
option java_multiple_files = true;

service PokemonPricesService {
  rpc GetPricesBatch (GetPricesBatchRequest) returns (GetPricesBatchResponse);
}

message CardPriceRequest {
  optional string card_id = 1;
  optional string name = 2;
  optional string set = 3;
}

message PriceSummary {
  optional string card_id = 1;
  optional double average = 2;
  optional double p10 = 3;
  optional double p50 = 4;
  optional double p90 = 5;
  optional double p99 = 6;
}

message GetPricesBatchRequest {
  repeated CardPriceRequest cards = 1;
}

message GetPricesBatchResponse {
  map<string, PriceSummary> prices = 1;
}
